[[clubs]]
url = "https://playtomic.com/clubs/padel-pl-wroclaw"
sport_id = "PADEL"

[[clubs]]
url = "https://playtomic.com/clubs/fiesta-padel"
sport_id = "PADEL"

[watch]
look_ahead_days = 30
minimum_notice_minutes = 0
state_path = "state/availability_state.json"

[[watch_windows]]
days = ["mon", "tue", "wed", "thu", "fri"] # list of values: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
start = "17:30"
end = "20:00"

[[notification_windows]]
days = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]
start = "08:00"
end = "22:00"

[filters]
required_features = ["double"]
excluded_name_substrings = ["single"]
include_resource_names = []
exclude_resource_names = []
allowed_durations = [90] # [60, 90, 120]

[notifications]
providers = ["telegram"]
notify_when_no_new_slots = true
